source "https://rubygems.org"

gem "rails", "4.2.1"
gem "sass-rails", "5.0.6"
gem "bootstrap-sass", "3.3.6"
gem "jquery-rails"
gem "turbolinks"
gem "uglifier", ">= 1.3.0"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "mysql2", "0.3.20"
gem "config", "1.0.0"
gem "devise"

group :development, :test do
  gem "letter_opener"
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
end
