default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: nganluong

test:
  <<: *default
  database: nganluong_test

production:
  <<: *default
  database: nganluong
